# Generated by Django 5.1.4 on 2024-12-29 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_task_assigned_node_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='trust_index',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_queue', 'In Queue'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('validating', 'Validating'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
