# Generated by Django 5.1.4 on 2025-01-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_node_trust_index_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='resources_usage',
            new_name='free_resources',
        ),
    ]
