# Generated by Django 5.1.4 on 2025-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_rename_resources_usage_node_free_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_queue', 'In Queue'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('validating', 'Validating'), ('validated', 'Validated'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
