# Generated by Django 5.1.4 on 2025-06-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_task_submitted_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('node', 'task')},
        ),
    ]
