# Generated by Django 5.1.4 on 2025-06-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_taskassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='validated',
        ),
    ]
