services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    ports:
      - "18080:5173"
    restart: always
    environment:
      - VITE_API_BASE_URL=http://localhost:18000/api
      - VITE_LOCAL_API_BASE_URL=http://localhost:18001/api
      - VITE_APP_TITLE=DistriCloud
      - VITE_ENABLE_DEBUG=true

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "18001:18001"
    restart: always
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HUB_API_BASE_URL=http://host.docker.internal:18000/api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: python node_local_server.py
